CardPatient/Controllers/CustomerPatientController.cs
using CardPatient.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CardPatient.Mediator.WorkWithPatient;

namespace CardPatient.Controllers
{
    public class CustomerPatientController : Controller
    {
        // GET: CustomerPatient
        public ActionResult CustomerPatients()
        {
            PatientMediator patientMediator = new PatientMediator();
                return View(patientMediator.GetListOfPatients());
        }
    
        public ActionResult Edit(int id)
        {
            PatientMediator patientMediator = new PatientMediator();
            return View(patientMediator.GetCurrentPatientById(id));
        }
        [HttpPost]
        public ActionResult Edit(int id, patients patient)
        {
            PatientMediator patientMediator = new PatientMediator();
            if (patientMediator.EditCurrentPatient(id, patient))
            {
                return RedirectToAction("CustomerPatients");
            }
            else
            {
                return View();
            }
        }
        public ActionResult Delete(int id)
        {
            PatientMediator patientMediator = new PatientMediator();
            return View(patientMediator.GetCurrentPatientById(id));
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            PatientMediator patientMediator = new PatientMediator();
            if (patientMediator.DeleteCurrentUser(id, collection))
            {
                return RedirectToAction("CustomerPatients");
            }
            else
            {
                return View();
            }
        }
        public ActionResult Search(string searchingUin)
        {
            PatientMediator patientMediator = new PatientMediator();
            var patient = patientMediator.SearchCurrentPatient(searchingUin);
            if (patient == null)
            {
                return RedirectToAction("CustomerPatients");
            }
            else
            {
                return View("Search", patient);
            }
        }
    }
}

CardPatient/Controllers/VisitHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CardPatient.Mediator.WorkWithVisitHistory;
using CardPatient.Models;

namespace CardPatient.Controllers
{
    public class VisitHistoryController : Controller
    {
        // GET: VisitHistory
        [HttpGet]   
        public ActionResult FillVisit(int id=0)
        {
            FillVisitMediator fillVisit = new FillVisitMediator();
            return View(fillVisit.VisitForm());
        }
        [HttpPost]
        public ActionResult FillVisit(visitHistory visit)
        {
            FillVisitMediator fillVisit = new FillVisitMediator();
            if (fillVisit.AddVisitToVisitHistory(visit))
            {
                ModelState.Clear();
                ViewBag.SuccesMessage = "succeful";
                return View("FillVisit", fillVisit.VisitForm());
            }
            else
            {
                return RedirectToAction("FillVisit");
            }
        }
    }
}

CardPatient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Добавить посещение", "FillVisit", "VisitHistory")</li>
                    <li>@Html.ActionLink("Изменение и поиск пациентов", "CustomerPatients", "CustomerPatient")</li>
                    <li>@Html.ActionLink("Добавить пациента", "AddPatient", "patient")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>